# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  calcmvcweb:
    image: calcmvcweb
    build:
      context: .
      dockerfile: CalcMvcWeb/Dockerfile
    ports:
      - 5000:5000
