apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: mvc-app
          image: ravikushwaha18rk/calcmvcweb:latest
          ports:
            - containerPort: 80